### ISSUE TITLE
Script broken since yesterday?

### ISSUE THREAD

**Issue by hans-juergen** [RudeySH/lastfm-bulk-edit#1]
Hi, since yesterday I cannot edit scrobbles with it anymore, it is "Waiting for Last.fm..." endlessly after editing something, so I have to refresh the browser tab to close the editor window with the circling image.

Manual editing the same scrobbles with the usual method does still work though.

I noticed that the editor window looks a bit different now: the active boxes or lines have a shadow or bright shining around the edges now. Don't know where that comes from and who changed it. There was a silent site update yesterday evening which might have to do with it. I use a dark mode userscript in Opera as well, so my editor window is in dark grey:

![Bulk Editor new look](https://user-images.githubusercontent.com/4970867/77035257-6cddfb80-69ac-11ea-8dfe-8567e3ef6659.png)

Also it is possible to checkmark the box at the bottom now which usually was blocked and showed a red icon when hovering it which does not appear anymore.

**Comment by RudeySH** [comment]
Thanks for reporting this issue. The latest version, v0.2.1, should fix this issue.

Apparently Last.fm made a tiny change to the scrobble edit dialog. The first frame after it is loaded, it does not contain any elements yet. The userscript now waits 1 frame before it starts to augment the scrobble edit dialog.

**Comment by hans-juergen** [comment]
Does your script update automatically, or do I have to do anything?

**Comment by RudeySH** [comment]
Yes, that works. Installing the script while it's already installed will also make it update. Automatic updates is not possible though.

**Comment by hans-juergen** [comment]
I tried it first in Opera, but did not restart the browser, so that is probably the reason why it did not work then.

I started Edge Chromium afterwards which also installed a new Tampermonkey version and tried bulk editing again, also with version 0.2.1, and that worked, both in normal and in dark mode. Thanks again!
