### ISSUE TITLE
Stuck on "Loading Scrobbles" screen (0%)

### ISSUE THREAD

**Issue by DexterVane** [RudeySH/lastfm-bulk-edit#11]
Just added the extension and I can't edit anything because when I try to, I get the "Loading Scrobbles" screen permanently. It stays at 0% and the loading-circle is turning.

Very new to Gitub and stuff like this, so it might be my mistake. 

Thank you! :)

(Chrome Version 90.0.4430.93, 64-Bit)

EDIT: Lastfm bulk edit Version 0.3.4
EDIT1: Tampermonkey V4.12

**Comment by RudeySH** [comment]
Do you have a Last.fm Pro subscription? 

If you do, then I'm not sure what causes your issue. Try disabling any ad/content blocker you might've installed on Chrome.

**Comment by DexterVane** [comment]
> Do you have a Last.fm Pro subscription?
> 
> If you do, then I'm not sure what causes your issue. Try disabling any ad/content blocker you might've installed on Chrome.

I do not have the Pro Subscription. I Apologise for not reading closely enough. Thanks anyway! Consider this solved :P
