### ISSUE TITLE
[Android] Hovering over Albums or Artists doesn't show anything.

### ISSUE THREAD

**Issue by Harmonie666** [RudeySH/lastfm-bulk-edit#16]
I'm not sure how to explain this issue, since I'm not a native english speaker. But when I'm using   this tool with Firefox Nightly in Android, then I don't see the albums or artists when I tap on them, or long press.

https://user-images.githubusercontent.com/73917917/153784811-4f84b11a-d9af-4ad1-9025-61602981f9e8.mp4

**Comment by RudeySH** [comment]
It's looks better now on v0.5.1:

![image](https://user-images.githubusercontent.com/3918757/153889218-0c218c31-48ee-47aa-9e74-45c03dd1ce47.png)

**Comment by Harmonie666** [comment]
> It looks better now on v0.5.1:
> 
> ![image](https://user-images.githubusercontent.com/3918757/153889218-0c218c31-48ee-47aa-9e74-45c03dd1ce47.png)

This is definitely better! Thanks for the fast and nice improvement. Will definitely try this out. 

Is it also technically possible to insert images to the text? Like Album cover, Artist picture?

**Comment by Harmonie666** [comment]
@RudeySH 

I dm'd you in Reddit but you probably didn't see it. So I'm putting it here:

I hope you don't mind me asking, were you able to work around the Firefox bug?

u/heildengoettern

**Comment by RudeySH** [comment]
@Harmonie666 I just opened a new issue (#17) for the Firefox bug we discussed on Reddit. I have no fix yet.

**Comment by Harmonie666** [comment]
Gochu. Thanks for the heads up :)
