### ISSUE TITLE
Trying to edit scrobble results in error FormData constructor: Argument 1 is not an object.

### ISSUE THREAD

**Issue by LeviOP** [RudeySH/lastfm-bulk-edit#18]
Pressing the edit scrobble button results in the "Loading Scrobbles..." screen showing up with it sitting at 0% and never doing anything. Checking the console, there has been an error: 
```
Uncaught (in promise) TypeError: FormData constructor: Argument 1 is not an object.
    scrobbleData moz-extension://11fa7aaa-a641-462d-ae7d-37fd0aa555c2/ Last.fm Bulk Edit.user.js#5:587
    result moz-extension://11fa7aaa-a641-462d-ae7d-37fd0aa555c2/ Last.fm Bulk Edit.user.js#5:663
    forEachParallel moz-extension://11fa7aaa-a641-462d-ae7d-37fd0aa555c2/ Last.fm Bulk Edit.user.js#5:662
    scrobbleData moz-extension://11fa7aaa-a641-462d-ae7d-37fd0aa555c2/ Last.fm Bulk Edit.user.js#5:578
```
I'm using firefox with voilentmonkey.

**Comment by RudeySH** [comment]
Do you have Last.fm Pro?

**Comment by LeviOP** [comment]
I thought that this worked by deleting and rescrobbling the scrobbles with new info. I should have read that you needed pro, totally my bad. Consider add an onscreen warning that you need pro, though ;)
