### ISSUE TITLE
The Loading Scrobbles surface is stuck at 0%

### ISSUE THREAD

**Issue by Aqueasim** [RudeySH/lastfm-bulk-edit#20]

**Comment by RudeySH** [comment]
What version of the script are you running? Do you have Last.fm Pro?

**Comment by RudeySH** [comment]
I suspect that you don't have Last.fm Pro. It explains why the script can't load your scrobbles, and it gets stuck on 0%.

Is this your profile? https://github.com/Aqueasim

The latest version of the script (v0.5.3) should show you a warning when trying to use the script without Pro, hope that clears up any confusion.
