### ISSUE TITLE
[enhancement] Merge different albums under different album artists

### ISSUE THREAD

**Issue by Aktimoose** [RudeySH/lastfm-bulk-edit#21]
I have a lot of scrobbles for an album that have different album artists recorded (due to the iOS last.fm app recording the track artist as the album artist), and I'd like to be able to merge them all to be under the correct album artist.

All of these different albums have been created due to the different track artists on the one singular album, and there doesn't seem to be a way to edit all of them at once
![image](https://user-images.githubusercontent.com/44620677/189891419-07af4105-90eb-4264-9475-24ed71b73610.png)

**Comment by RudeySH** [comment]
If you scrobble the entire album once with the correct album artist, it should be a lot easier to merge them. For example, if you scrobble all those tracks using the album artist "SilvaGunner", afterwards you should go to `https://www.last.fm/user/_/library/music/SilvaGunner` where you can edit scrobbles for the entire album at once, and then  fix all the scrobbles that were scrobbled with an incorrect album artist.
