### ISSUE TITLE
scrobbles not merging

### ISSUE THREAD

**Issue by kiwistarfru1t** [RudeySH/lastfm-bulk-edit#22]
hi! whenever i make edits the scrobbles wont merge, not sure what im doing wrong

**Comment by RudeySH** [comment]
Hi. Do you have a Last.fm Pro subscription? That is required for this script to be able to make edits.

**Comment by kiwistarfru1t** [comment]
hi yes i do! it actually finally worked for me i just had to reload a
couple times!

**Comment by aeeon** [comment]
I can confirm, it's problem with violentmonkey for firefox. I switched to tampermonkey and everything works.

**Comment by RudeySH** [comment]
I'm unable to reproduce any issues with Firefox/Violentmonkey.

I'm using:

- Firefox 108.0.2 (64-bit)
- Violentmonkey v2.13.7
- Windows 10 Pro (build 19045.2364)

What issue were you having, exactly? Does the "edit scrobbles" menu item no longer show up? Or does it show up, but it simply didn't load anything? Or did it load your scrobbles, but your edits were not going through?
