### ISSUE TITLE
is it not working atm?

### ISSUE THREAD

**Issue by babyhow** [RudeySH/lastfm-bulk-edit#26]
the loading scrobbles box keeps loading endlessly i'm not sure if it's just me

**Comment by supername182** [comment]
same problem here

**Comment by DIZZYDJC** [comment]
same problem here sadly

**Comment by eamezey1** [comment]
Same - glad it's not just me, thought it might have been a Chrome extension issue. It seems to still work on individual tracks, just not on the main artist page.

**Comment by lauramachts** [comment]
Same, I've tested in two browsers thinking the problem was my main browser. I can't edit anything...

**Comment by RudeySH** [comment]
I'm working on a fix. I will keep you updated!

**Comment by RudeySH** [comment]
I just fixed the endless loading issue, as well as some other issues (duplicate "Edit scrobbles" buttons, modals not closing).

Update the Last.fm Bulk Edit userscript to version 1.2.0. To update the script, use the dashboard of your userscript manager (Violentmonkey/Tampermonkey). Alternatively, you can update the script by simply doing step 3 from the [instructions](https://github.com/RudeySH/lastfm-bulk-edit#instructions) again.
