### ISSUE TITLE
"Select/deselect all" albums when editing artist

### ISSUE THREAD

**Issue by hans-juergen** [RudeySH/lastfm-bulk-edit#3]
I just edited some classical music albums by Antonio Vivaldi. When I started by editing the artist from my library, I had all his albums selected on default in the Edit window which is a very long list. As I only wanted to edit some albums there, I had to manually deselect this list. It would save some time if there was a checkbox for deselecting and/or selecting all albums on top of that Edit window.

By the way, is there a way to start editing my artist scrobbles from the global artist page, e.g. from my avatar and the personal scrobble counter there? I know I already asked this on Reddit, and you wanted to check if it could be realised. Having to find the artist in my library can take some time, e.g. for an artist with not so many scrobbles, as the library is quite big.

**Comment by RudeySH** [comment]
I just added buttons to select/deselect all albums (commit ec61c4b644808c152767dea2a62383a56250e765). Version 0.2.4 of the script includes these buttons. As a reminder, to update the userscript, just install it again (see the instructions in the readme here: https://github.com/RudeySH/lastfm-bulk-edit)

I'll create a new issue for your other suggestion.

**Comment by hans-juergen** [comment]
Thanks a lot!
