### ISSUE TITLE
No scrobble fetching, when loading scrobbles from artist or album in any dialogue.

### ISSUE THREAD

**Issue by cube-industries-cubel** [RudeySH/lastfm-bulk-edit#31]
When selecting (and fetching) scrobbles from an artist or album to edit, it seemingly infinitely loads and from looking at the console and the network, it seems like nothing is even happening. The issue with the console errors seems to be the "FormData" constructor, wherein the argument being passed to it is not an object in last.fm.
The errors (to me) seem to just be the issue cascading throughout the code itself.
![wessadw2a](https://github.com/RudeySH/lastfm-bulk-edit/assets/89550767/d208bed5-aa1c-478f-ae4d-0dc3ce3d3c1e)
The network console seems to indicate that the scrobbles aren't even being fetched in the first place, and therefore not able to load in the modal due to not actually being fetched. 
![Captud2wd2assdadswware](https://github.com/RudeySH/lastfm-bulk-edit/assets/89550767/61a26e1f-d476-4919-bd23-4297a0839be1)
(previously it had just been getting the loading circle gif over and over, this is probably just profile information that's loading)
This error is not related to any of my extensions, or firefox itself, as far as I am aware.
![Captu23aesssare](https://github.com/RudeySH/lastfm-bulk-edit/assets/89550767/fb5142c5-f89b-4002-b56b-ea75219984ec)
(also just as an aside, a percentage is not displayed anywhere while loading, that specifically could be due to darkreader, but I am not sure, I just saw it in the script and thought I should tell you)
hopefully this makes sense at all, I don't have much experience with programming really at all, let alone js.

**Comment by RudeySH** [comment]
This sounds a lot like an issue that was recently fixed. What version of the script are you using? v1.3.3 is the latest version.

**Comment by cube-industries-cubel** [comment]
oh my god im so sorry 
i had just downloaded the script from tampermonkey and didnt even check. thanks for letting me know
