### ISSUE TITLE
unable to bulk edit

### ISSUE THREAD

**Issue by GabingIn3D** [RudeySH/lastfm-bulk-edit#32]
I've included images because this seems to be very specific. 'Edit scrobbles' on my profile homepage will show "Loading scrobbles" forever. It also does this when attempting to choose 'Edit scrobbles' on albums. Currently, the only way for me to bulk edit is to go to the track page and use 'Edit scrobble' on a specific timestamp in my Library and then have it 'Apply to new scrobbles of this track' or use the merge tool. The biggest drawback seems to be that to change an album title/merge an album, I must edit them track-by-track from Library/Tracks and then click on the track name to find a specific instance of a historic scrobble.

The last image shows the only current way I can bulk edit tracks away from the main profile page.

I'm also aware the possibility could lie in Last.fm itself, I just thought I'd raise this issue. I've tried disabling and re-enabling the Last.fm bulk edit extension, logging out and logging back in. I've used this tool (thank you so much by the way) for a long time now, but it seems to have been this way for at least several months.
![lastfm_albumedit](https://github.com/RudeySH/lastfm-bulk-edit/assets/122047218/f56c1729-4e88-405b-888a-9f9a0f7f9248)
![lastfm_trackeditrecent](https://github.com/RudeySH/lastfm-bulk-edit/assets/122047218/6cead95d-70a5-4d62-ad25-868ea6099228)
![lastfm_trackedit](https://github.com/RudeySH/lastfm-bulk-edit/assets/122047218/6a469ef4-e47f-450f-8106-4c5129d1ea58)

**Comment by RudeySH** [comment]
This sounds a lot like an issue that was recently fixed. What version of the script are you using? v1.3.3 is the latest version.

**Comment by Dgro82** [comment]
I've had the exact same issue. I reinstalled Violentmonkey and the script today, so I have the latest version, but nothing doing. Am using Brave browser.

**Comment by RudeySH** [comment]
Did you install the script via greasyfork.org? If so, you do not have the latest version. Please ensure you have the latest version (v1.3.5 as of now) by installing the script directly from GitHub. To update the script, do step 3 from the installation instructions [here](https://github.com/RudeySH/lastfm-bulk-edit#instructions).

**Comment by kevinspencer** [comment]
Just a quick note to say uninstalling and installing v1.3.5 solved the issue for me.  My original install into Violentmonkey was stuck at an old version.  Also, thank you very very much for this script.  Has made last.fm infinitely more usuable for me.
