### ISSUE TITLE
violentmonkey

### ISSUE THREAD

**Issue by bnuuyhop** [RudeySH/lastfm-bulk-edit#33]
when i downloaded this script from violentmonkey it only gave me the 1.0.0 version. Are you able to fix that?

**Comment by RudeySH** [comment]
Do you mean you downloaded this script from greasyfork.org? Violentmonkey does not host scripts, so you can't have downloaded it directly from them.

Thanks for pointing this out, greasyfork.org only had up to v1.0.0. It should now automatically have the latest version.

However, I do not recommend installing scripts via greasyfork.org, if possible install them directly from GitHub.
