### ISSUE TITLE
Albums not showing below the inbox

### ISSUE THREAD

**Issue by ikuya2015** [RudeySH/lastfm-bulk-edit#34]
I've uploaded a picture. As it shows, the alternatives for albums (and albums artists) are not showing when I click the inbox anymore. However the track inbox functions normally.
![image](https://github.com/RudeySH/lastfm-bulk-edit/assets/72790724/b09021ee-8061-4076-9c68-0ff8e827de18)

**Comment by ikuya2015** [comment]
Seems it's been fixed these days?

**Comment by RudeySH** [comment]
I haven't changed anything, but I'm glad to hear the issue has resolved itself.
