### ISSUE TITLE
Request: Automatically use “Artist” as “Album Artist” when album artist is blank

### ISSUE THREAD

**Issue by salazarbarrera** [RudeySH/lastfm-bulk-edit#36]
Related to [this proposal in Last.fm community support](https://support.last.fm/t/automatically-use-artist-as-album-artist-when-adding-an-album-info-to-a-scrobble/90327), but focused on this bulk editor.

Basically what the title says. If the Album Artist is blank, do some of these or equivalent:

-  Visually autocomplete the "Album Artist" with the "Artist" and let the user erase it if they want
- After pressing "save edit", warn the user that the Album Artist is blank, that it will fail, and ask if they want to fill it with Artist?   
- Just autocomplete it without asking (this the [Web Scrobbler](https://web-scrobbler.com/) way)

**Comment by salazarbarrera** [comment]
I can help with the programming, but the three alternatives proposed are very opinionated, and I think you as the maintainer should say which one you would prefer (if any) before putting my hands on the keyboard and start coding.

**Comment by RudeySH** [comment]
I haven't quite implemented what you asked for, but I hope this is good enough: I made two changes:

1. The album and album artist fields will now become red when the field is empty while the other field is not empty.
2. The "Save Edit" button becomes disabled when any of the fields have a validation error (= red).

![image](https://github.com/RudeySH/lastfm-bulk-edit/assets/3918757/3559e46c-1f92-4abd-965d-1e3a323fa32c)

Update the script to v1.4.1 to try this out.
