### ISSUE TITLE
lastfm-bulk-edit not active on Last.fm anymore

### ISSUE THREAD

**Issue by hans-juergen** [RudeySH/lastfm-bulk-edit#38]
I updated MS Edge to a new version today, and now the script is not active anymore, but Tampermonkey still shows it as enabled:
![image](https://github.com/RudeySH/lastfm-bulk-edit/assets/4970867/8cd9969f-b407-4ceb-87b1-36fceeb19679)

Microsoft Edge Version 125.0.2535.67 (Offizielles Build) (64-Bit)

There is no Edit option in the dropdown menu of a track or on artist pages in my library anymore, the albums do not show in my recent tracks anymore etc.

**Comment by hans-juergen** [comment]
Everything back to normal now, don't know what happened.

**Comment by hans-juergen** [comment]
Weird.

**Comment by RudeySH** [comment]
Half a day ago, I had the same issue with Edge and Tampermonkey but with a different script. Could've been an issue with Edge or Tampermonkey, not sure.
