### ISSUE TITLE
Unable to edit all scrobbles on a sinlge artist (Album field error)

### ISSUE THREAD

**Issue by s0mnam** [RudeySH/lastfm-bulk-edit#42]
Pretty much as described above - appears to be the case on all artists. Does not occur if only one album has been scrobbled; also if one is selected from the dropdown.
(Additionally, last.fm seems to have rate limited me after 5% on a larger, 6k scrobble edit attempt :D)

I'm using Violentmonkey, updated to newest version, 2nd attempt, screenshots from that.

Some screenshots in case it's unclear:

1. Opening menu, highlighted to be removed
![grafik](https://github.com/user-attachments/assets/3470a4bf-f7db-4520-9088-46d099b719d7)

2. Letter removed, album box immediately throws error, save button greyed out
![grafik](https://github.com/user-attachments/assets/fff2b8ca-b6c2-4c2a-8138-febb1ec426de)

**Comment by s0mnam** [comment]
Console output on another artist, but I believe it should be replicable
![grafik](https://github.com/user-attachments/assets/12fa9b7e-c158-4cae-bc15-b5eeead916d0)

**Comment by RudeySH** [comment]
I just fixed this. Update the script to version 1.5.3 and try again :)
