### ISSUE TITLE
Auto-Edits in a different site language than English

### ISSUE THREAD

**Issue by hans-juergen** [RudeySH/lastfm-bulk-edit#43]
Hi @RudeySH, I just noticed that when using a different site language than English on the auto-edit overview (German in my case), your script does not add its additional features anymore like bold font for showing the new edits or the navigation scrollbar on top:

https://www.last.fm/de/settings/subscription/automatic-edits

**Comment by RudeySH** [comment]
Nice find! I just fixed this in version 1.5.4.

I never switched languages on Last.fm before, so I didn't realize that it adds the country code to all URLs.

**Comment by hans-juergen** [comment]
Thank you for the quick fix!
