### ISSUE TITLE
"No Album" text showing under every album in an artist's page in your library

### ISSUE THREAD

**Issue by Chaitius** [RudeySH/lastfm-bulk-edit#45]
![noalbum](https://github.com/user-attachments/assets/59e69615-e287-4b63-b63e-4a1967cfeeff)
This is quite new, any reason this is happening? I disabled the extension to verify it's indeed due to this script

**Comment by RudeySH** [comment]
I'll have to look into this next week, when I'm back from vacation.

**Comment by Wolvpak** [comment]
Same issue here, on both Chrome and Firefox, using Violentmonkey

**Comment by kirundist** [comment]
Same here, using v1.5.7 of the script on Tampermonkey for Firefox.  Only started happening in the last week or so.

**Comment by RudeySH** [comment]
This is now fixed in version 1.5.8.
