### ISSUE TITLE
Bulk edit stopped working

### ISSUE THREAD

**Issue by fbnxe** [RudeySH/lastfm-bulk-edit#47]
For some reason I'm not able to edit anything anymore...
![Error](https://github.com/user-attachments/assets/57d0002d-e5ad-4ff4-a124-f29fab72a80e)

**Comment by JosephStyles11** [comment]
This is happening for me too - also not displaying the albums of each track under "Recent Tracks". I'm using Google Chrome and the extension is enabled via Tampermonkey.

![image](https://github.com/user-attachments/assets/adfb18dc-fab7-46bd-be9d-209579c50d40)

**Comment by yaniv-sellersnap** [comment]
same here, seems like the script has stopped working entirely

**Comment by JosephStyles11** [comment]
Hi,

Thanks for the update. I had the updated versions of Chrome and the bulk editor, and both Tampermonkey and the script were enabled.

I tried through Violentmonkey and the script is working there.

**Comment by thereddestdog** [comment]
Maybe is Manifest V3 breaking things?

**Comment by azkore** [comment]
Looks like the site has updated and unfortunately the script is broken for me right now.

**Comment by ML72-0** [comment]
> Looks like the site has updated and unfortunately the script is broken for me right now.

The exact same thing is happening to me.

**Comment by RudeySH** [comment]
This thread is about an issue from before today, for some users the extension appears to have stopped working entirely in certain browsers.

For issues caused by today's Last.fm site update, please go this issue instead: #50.

**Comment by thereddestdog** [comment]
> Are there still users in here that can't get the script to work at all in Tampermonkey? If so, are you experiencing this issue in Chrome? Does Tampermonkey in a different browser (i.e. Edge or Firefox) work?
> 
> (The script has been updated to fix the other issues caused by Last.fm's site update.)

I use TamperMonkey on FireFox and I have no issues since you updated 👍
