### ISSUE TITLE
Bulk editing is completely broken since today's Last.fm site update

### ISSUE THREAD

**Issue by RudeySH** [RudeySH/lastfm-bulk-edit#50]
The "Edit scrobbles" menu still shows up, but when you use it, it doesn't load properly. Afterwards the Last.fm page gets a weird layout bug, see screenshot.

(This screenshot is not cropped poorly, the left 40% of the screen actually becomes black.)

![image](https://github.com/user-attachments/assets/1a5379d8-009e-4a27-ba0a-b0aad5d6f144)

I'm currently at work and won't have much time later today, but I'll try to get this fixed in the weekend.

**Comment by thereddestdog** [comment]
More info on other newly added features from Last.fm:

https://support.last.fm/t/editing-scrobbles-last-fm-pro-feature/187

**Comment by hans-juergen** [comment]
The new explanations from today about album editing etc. are at the bottom of that older announcement:
https://support.last.fm/t/editing-scrobbles-last-fm-pro-feature/187/3

**Comment by RudeySH** [comment]
Bulk scrobble editing is working again! Please update the script to version 1.6. Let me know if there are still issues.

**Comment by Smithsix** [comment]
Works like a hot damn, near as I can tell.

Thanks very much.

**Comment by kirundist** [comment]
Works perfectly again, thank you!

**Comment by abrown19** [comment]
Rudey, Thank you so much for the quick update!
