### ISSUE TITLE
Edit an artist from the artist page

### ISSUE THREAD

**Issue by RudeySH** [RudeySH/lastfm-bulk-edit#6]
In #3, user @hans-juergen suggested the following:

> Is there a way to start editing my artist scrobbles from the global artist page, e.g. from my avatar and the personal scrobble counter there? Having to find the artist in my library can take some time, e.g. for an artist with not so many scrobbles, as the library is quite big.

**Comment by RudeySH** [comment]
Version 0.3.0 (commit 7fea1310dcf9f08f4ef5c8635a873efc7e351c85) adds a "Edit scrobbles" option to the header of various library pages:

![image](https://user-images.githubusercontent.com/3918757/111547859-1a2f4f00-877a-11eb-98cf-5a29eacb65cc.png)

This change affects artist pages, album pages and track pages. Note that it does not add the Edit option to the global artist page, which was originally asked, but it's only one click to navigate from a global artist page to the user's library artist page, so I think it's fine the way it is now.

**Comment by hans-juergen** [comment]
Great, thank you! That should make it easier to access the bulk edit option for artist names now. After updating the script version to 3.0 I had to refresh an artist library page with Ctrl+F5 to show the new link, but now it works.

**Comment by hans-juergen** [comment]
Oops, it seems that the new Edit Scrobbles option also appears when checking other users' libraries. It only shows "Loading Scrobbles..." at 0% then, but this should be avoided.

**Comment by RudeySH** [comment]
Good call, that's fixed in v0.3.1
