### ISSUE TITLE
Sorting the artist overview e.g. "no album" at the top or bottom

### ISSUE THREAD

**Issue by hans-juergen** [RudeySH/lastfm-bulk-edit#7]
As your userscript is one of the few tools that can actually show all scrobbles with no album info for an artist, it might be useful to either sort the overview with "no album" scrobbles at the top or offer an option to show only those perhaps. That way you could quickly find all the scrobbles you made e.g. on YouTube and/or with the Last.fm player and YouTube playback which do not have album and album artist info. Also imported scrobbles from Spotify are missing them, because their standard StreamingHistory.json files do not contain album and album artist info (the ones from the complete Spotify account data do though).

**Comment by RudeySH** [comment]
Version 0.3.2 (edc25252acd33a276f459a60401f8da21b75c19f) is out now, and it moves "No album" to the top and colors it red. Is this sufficient?

![image](https://user-images.githubusercontent.com/3918757/111694795-a2712b00-8832-11eb-96c3-ba9b4c16fdd8.png)

**Comment by hans-juergen** [comment]
Looks good, thank you again!
